### ISSUE TITLE
Performance of linesUnbounded not linear wrt. line length

### ISSUE THREAD

**Issue by Oblosys** [snoyberg/mono-traversable#110]
Because `Data.Conduit.Combinators.splitOnUnboundedEC` `mappend`s each chunk and `break`s on the result, `linesUnbounded` becomes inefficient when line length exceeds the chunk size. In case of strict byte strings or lists, this also has unnecessary memory costs.

The code below starts printing out numbers quickly, and gradually slows down until it reaches 300, after which it speeds up again.

```
slow :: IO ()
slow = do
  counterVar <- newIORef 0
  void . runResourceT $
    runConduit $     longLineSrc
                 =$= CL.mapM (\bs -> liftIO $ do
                                modifyIORef counterVar (+1)
                                i <- readIORef counterVar
                                putStrLn $ show i
                                return $ bs :: IO BS.ByteString)
                 =$= CC.linesUnboundedAscii
                 =$= CL.consume
    where longLineSrc :: ConduitM () BS.ByteString (ResourceT IO) ()
          longLineSrc = loop
             where loop = do
                     replicateM 300 $ yield chunk
                     yield $ BS.pack "\n"
                     loop
                   chunk = BS.replicate (100*1024) 'x'
```

**Comment by snoyberg** [comment]
I'm going to be mostly unavailable for the next week, but if you'd like to
send a PR I'll be able to review more quickly.

**Comment by Oblosys** [comment]
There you go.

**Comment by snoyberg** [comment]
Very quick, and nice patch. Thank you!

**Comment by Oblosys** [comment]
That was a very fast merge, thanks!
