### ISSUE TITLE
`index` i === listToMaybe for negative indices

### ISSUE THREAD

**Issue by richsmith92** [snoyberg/mono-traversable#114]
```
> index [1,2,3] (-1)
Just 1
> index [] (-1)
Nothing
```

I expected `Nothing` to be the result in both cases. Can we consider tis behavior a bug, or there is some reasoning behind it?

**Comment by snoyberg** [comment]
I don't have a strong feeling on this in any direction, I'd be OK with changing it (or even throwing an exception as invalid input).

**Comment by BebeSparkelSparkel** [comment]
fixed by #173
