### ISSUE TITLE
`conduit-combinator` fails to build documentation due to inaccurate version bounds in `conduit`

### ISSUE THREAD

**Issue by hvr** [snoyberg/mono-traversable#116]
See

https://hackage.haskell.org/package/conduit-combinators-1.0.8.2/reports/

for details. NB: It's not Hackage's fault that the documentation could not be built.

**Comment by snoyberg** [comment]
Guess again https://github.com/snoyberg/conduit/issues/288. NB: PVP didn't prevent this.

**Comment by hvr** [comment]
NB: I didn't mention PVP at all

**Comment by snoyberg** [comment]
Never said you did. But you did say inaccurate version bounds.

**Comment by hvr** [comment]
Fair enough, I stand corrected. But since the PVP got mentioned, it was a result of failing to follow the PVP. Obviously the PVP can't prevent this unless it's actually been upheld by both parties to the contract. Fwiw, a similiar PVP violation just slipped into the Cabal 1.24.1.0 release which will likely have to be redacted asap

**Comment by snoyberg** [comment]
Given that there's no bug at all in conduit-combinators, can we close this issue?

**Comment by hvr** [comment]
sure

**Comment by hvr** [comment]
PS: Clearly, we need to polish the tooling to help detect cases where a version increment doesn't reflect the severity of the API changes. While it may not detect 100% cases, it would already help if it could point to potential problems.
