### ISSUE TITLE
How about changing whenM to take m a?

### ISSUE THREAD

**Issue by jeiea** [snoyberg/mono-traversable#123]
Currently all your preludes export `whenM :: m Bool -> m () -> m ()` intactly from `Control.Monad`.
If I use `act :: IO a` with `whenM`, then it would be `whenM mpred (act >> return ())`.
It can be bypassed by changing the signature to `m Bool -> m a -> m ()`. And I think  `when` is also considerable. How do you think?

**Comment by snoyberg** [comment]
I prefer the current signature, as it avoids bugs of accidentally ignoring
return values. This is a common debate on the haskell community.
