### ISSUE TITLE
Add sequence length function that returns (Index seq)

### ISSUE THREAD

**Issue by AshleyYakeley** [snoyberg/mono-traversable#126]
The `Index` type family is used throughout the library to point into sequences, in may cases with an `Integral` constraint (e.g., `take` and `drop`). It would be useful to have a length function that gave the length of a sequence as `Index seq`.

This is my current workaround, which should be correct in all cases:
```
indexLength :: (MonoFoldable seq,Integral (Index seq)) => seq -> Index seq
indexLength = fromIntegral . olength64
```

**Comment by snoyberg** [comment]
Looks reasonable. Want to send a PR?

**Comment by AshleyYakeley** [comment]
OK, https://github.com/snoyberg/mono-traversable/pull/127

**Comment by AshleyYakeley** [comment]
Thanks!
