### ISSUE TITLE
Eq key => SetContainer [key]

### ISSUE THREAD

**Issue by jchia** [snoyberg/mono-traversable#135]
Is there an intrinsic reason for having an instance `Eq key => SetContainer [(key, value)]` but not `Eq key => SetContainer [key]`? Because of this missing instance, `ClassyPrelude.(\\)` can't do the same thing as `Data.List.(\\)`.

**Comment by snoyberg** [comment]
The instance is impossible without something like OverlappingInstances, which would be a bad thing to add.
