### ISSUE TITLE
SetContainer, IsSet, IsMap proposals

### ISSUE THREAD

**Issue by richsmith92** [snoyberg/mono-traversable#15]
Hi guys, I really appreciate your extensive work on this front. I have some proposals here:

First and foremost, please split `Data.Containers` to Set and Map modules. We haskellers are used to `Data.Map`, `Data.Set` and similar interfaces, so `insertMap`, `insertSet`, `mapToList` and others are non-intuitive. Just use good old naming scheme (`insert`, `toList` etc.).

My second point is that `Map` is a kind of a set, isn't it? Actually `Map` can be viewed as set in three ways:
1. `Map` as a set of values, ignoring keys
2. `Map` as a set of keys, ignoring values
3. `Map` as a set of (key, value) pairs

Default view of a `Map` should be the first (like in Functor/Foldable/Traversable). Other views can be implemented with newtypes:

```
-- | View of a map as a set of keys, ignoring values
newtype Keys map = Keys { unKeys :: map }
type instance Element (Keys map) = ContainerKey map
type instance ContainerKey (Keys map) = ContainerKey map

-- | View of a map as a set of (key, value) pairs
newtype Assocs map = Assocs { unAssocs :: map }
type instance Element (Assocs map) = (ContainerKey map, Element map)
type instance ContainerKey (Assocs map) = (ContainerKey map, Element map)
```

Now we can write `insert` and `delete` functions for `IsMap` in terms of `IsSet` (assuming you renamed/moved `insertSet` to `IsSet.insert` and similar):

```
insert :: (IsSet (Assocs m)) -> ContainerKey m -> Element m -> m -> m
insert k v = unAssocs . IsSet.insert (k, v) . Assocs

delete :: (IsSet (Keys m)) -> ContainerKey m -> m -> m
delete k = unKeys . IsSet.delete k . Keys
```

So we can remove these (and similarly, list conversion) functions from `IsMap` class if we add constraints

```
(IsSet (Keys m), IsSet (Assocs m)) => IsMap m
```

Now, the problem is that we can't implement set insertion for `Keys` view, just like set delete for `Assocs` will be different from ordinary map delete. We can either make them produce `error`, or split `IsSet` into fine-grainer classes, `Deletable` and `Insertable`. I really prefer the second way. So the part of class constraint for `IsMap` will be

```
(Insertable (Assocs m), Deletable (Keys m)) => IsMap m
```

What do you think of this? I wrote the similar thing in past, with `Deletable`, `Insertable`, `Filterable` and `Sized` classes: [SetLike](https://github.com/w3rs/container-classes/blob/master/Data/SetLike.hs) for monomorphic (e.g. `IntSet`) and [MapLike](https://github.com/w3rs/container-classes/blob/master/Data/MapLike.hs) for polymorphic (e.g. `IntMap`) types

**Comment by fredefox** [comment]
Hello, I don't mean to resurrect this dead issue from the grave, but I just ran into a problem that I feel fit in nicely here. Maybe it's more of a question (in which case I apologize).

I wanted to provide

    filter :: IsMap map => (MapValue map -> Bool) -> map -> map

In the style of `Data.Map` from the `containers` package. However, I don't see a way to do this with the things that `IsMap` currently exports. Then I had a look at `IsSequence` but was surprised to see that `Map` is not (made) an instance of this.

Would it make sense to have such a function as I propose in general?

**Comment by snoyberg** [comment]
I'd be OK with adding such a function. Calling it `filterMap` seems like it
would fit in well.

**Comment by fredefox** [comment]
Incoming at #167.
