### ISSUE TITLE
add function fmapNonNull

### ISSUE THREAD

**Issue by cdepillabout** [snoyberg/mono-traversable#150]
When I am working with `NonNull` in a new codebase, I often reimplement the following function:

```haskell
fmapNonNull
  :: (Functor f, MonoFoldable (f b))
  => (a -> b) -> NonNull (f a) -> NonNull (f b)
fmapNonNull f = impureNonNull . fmap f . toNullable
```

This lets you call `fmap` on the underlying container in a `NonNull`.  Here's an example:

```haskell
> let nonNullable = impureNonNull [1,2,3] :: NonNull [Int]
> fmapNonNull show nonNullable :: NonNull [String]
["1","2","3"]
```

This is not possible with [`omap`](https://hackage.haskell.org/package/mono-traversable-1.0.5.0/docs/Data-MonoTraversable.html#t:MonoFunctor), because it does not let you change the type of the element in the underlying container.

I think this `fmapNonNull` would be widely useful, because `NonNull` is often used with `Functor`s like `[]` or `Seq`.

This function could go into the `Data.NonNull` module.

Here are some possible names for this function:

- fmapNonNull
- fmapNonNullable
- mapNonNull
- mapNonNullable

I think any of those four names would be suitable.

If the maintainers agree that this could go into `Data.NonNull`, I will send a PR to include it.

**Comment by snoyberg** [comment]
I have no objection, looks sensible. mapNonNull seems best to be.

**Comment by cdepillabout** [comment]
Added in #151.
