### ISSUE TITLE
Data.Sequences.sort

### ISSUE THREAD

**Issue by alexkazik** [snoyberg/mono-traversable#153]
Why is it defined as a dependency on IsSequence and not as follows?

sort :: (SemiSequence seq, Ord (Element seq)) => seq -> seq
sort = sortBy compare

(This way sort is only dependant on SemiSequence, which is a dependency for SemiSequence, thus less dependencies. Also sortOn is defined in such a way.)

**Comment by snoyberg** [comment]
Seems like that change should work, and I don't have an objection to it. Want to take a crack at a PR?

**Comment by snoyberg** [comment]
Fixed by #154, thanks!
