### ISSUE TITLE
`singleton` not implemented for `NonEmpty`; change constraint

### ISSUE THREAD

**Issue by gittywithexcitement** [snoyberg/mono-traversable#156]
### Problem:
`singleton` is not implemented for `NonEmpty`
This does not make sense; obviously you can create a `NonEmpty` from a single element.

### Details:

1. `singleton` has the constraint `IsSequence seq`. 
1. `Monoid` is a superclass of `IsSequence`
1. `NonEmpty` is not an instance `Monoid`. This makes sense because there's no valid `mempty`.
1. Thus `singleton` is not implemented for `NonEmpty`. This does not make sense because you can obviously create a valid `NonEmpty` container from a single element. The workaround is to use not-well-known functions like `opoint` or `pure` to create a `NonEmpty`. This makes my code less readable, because those functions are not well known (`opoint`) or not typically used to create a container (`pure`).

### Solution:

Change `singleton` constraint to `MonoPointed`. That's all.

The implementation of `singleton` is:
`singleton = opoint`
which only requires a `MonoPointed` constraint, as `opoint` is a function of that type class. `NonEmpty` already is an instance of `MonoPointed`, so after changing the constraint, `singleton` will be implemented for `NonEmpty`.

**Comment by snoyberg** [comment]
Sounds fine to me, want to send a PR?

**Comment by gittywithexcitement** [comment]
Will do.

I see that singleton is in Data.Sequence, but MonoPointed is in Data.MonoTraversable. Thus, it would make sense to move singleton, given the updated constraint, but that would break user code. What do you suggest?

**Comment by snoyberg** [comment]
What's the motivation for moving it? opoint already exists in
Data.MonoTraversable, and singleton is intended to complete the
Data.Sequence API for compatibility with libraries like text and bytestring.

**Comment by gittywithexcitement** [comment]
I see. Given that, I see no reason to move it.

**Comment by gittywithexcitement** [comment]
Thanks for the super fast feedback!
