### ISSUE TITLE
benchmark failing to build for 1.0.8.0 on stackage nightly

### ISSUE THREAD

**Issue by cdornan** [snoyberg/mono-traversable#158]
Building benchmark 'sorting' for mono-traversable-1.0.8.0..
[1 of 2] Compiling Main             ( bench/sorting.hs, dist/build/sorting/sorting-tmp/Main.o )

bench/sorting.hs:19:22: error:
    Not in scope: type constructor or class ‘Benchmark’
   |
19 | mkGroup :: Int -> IO Benchmark
   |                      ^^^^^^^^^

cc @snoyberg

**Comment by snoyberg** [comment]
Thanks, should be fixed in 1.0.8.1.
