### ISSUE TITLE
Textual -> Characters

### ISSUE THREAD

**Issue by gregwebs** [snoyberg/mono-traversable#17]
Text cannot just be treated as `[Char]`. For example, capitalization will not always work in such a circumstance. Therefore, the Textual functions toLower and toUpper do not treat Text as a sequence of characters.

I think we are missing a chance to come up with a better way of making this distinction and helping users operate on Text as a whole by default and only act on it as a sequence as necessary. My suggestion is to start by renaming Textual to Characters, but I am not sure where exactly to go from there. My end goal would be to have a Textual type in which every operation you needed was available but only "safe" functions were available that would prevent one from messing up unicode stuff. Textual is actually close to that now, but inheriting from IsSequence seems problematic.

**Comment by samvv** [comment]
@gregwebs I actually very much liked your idea. It makes sense. I was on a similar thought train myself. Is this really too ambitious for mono-traversable, though? All dependencies are there, it just requires some coding. @snoyberg would you accept pull requests for something like this? I can't promise anything (I'm still getting a firm grip on Haskell) but it sounds like this could be useful.

**Comment by samvv** [comment]
Ok, never mind me ... I naively thought the whole time that `Char` was equivalent to a C-style char, which it isn't. If I'm correct, then, Unicode should work out-of-the box with `Textual`? Correct me if I'm wrong.
