### ISSUE TITLE
NonNullToNonEmpty

### ISSUE THREAD

**Issue by MaxGabriel** [snoyberg/mono-traversable#184]
Mono-traversable has a nice interface for protecting against empty lists, but occasionally you do need to interface with something that asks for NonEmpty, such as [persistent-qq's `%{}` value replacement](https://hackage.haskell.org/package/persistent-qq-2.9.1/docs/Database-Persist-Sql-Raw-QQ.html).

Do you think adding a function to go from nonNullToNonEmpty would be reasonable? Something like:

```
nonNullToNonEmpty :: NonNull [a] -> NE.NonEmpty a
nonNullToNonEmpty nonNull = NE.fromList (toList nonNull)
```

**Comment by snoyberg** [comment]
Seems reasonable to me. What about upgrading to `nonNullToNonEmpty :: Foldable f => NonNull (f a) -> NE.NonEmpty a`, which I think should be fine.

**Comment by MaxGabriel** [comment]
I'm ok with that. I haven't looked at mono-traversable in awhile, but would it be better to use `MonoFoldable` or just regular `Foldable`?

```
toNonEmpty :: MonoFoldable mono => NonNull mono -> NE.NonEmpty (Element mono)
toNonEmpty = NE.fromList . otoList
```

**Comment by snoyberg** [comment]
Good point, that sounds better.
