### ISSUE TITLE
Doesn't build with ghc 8.2.1

### ISSUE THREAD

**Issue by phlummox** [snoyberg/mono-traversable#188]
This seems most likely to be a bug with ghc, but I mention it in case you can assist , and to let you know that mono-traversable may not compile with ghc 8.2.1.

I just had a travis build fail ([here](https://travis-ci.com/phlummox/stache/jobs/295613836)) while trying to build mono-traversable 1.0.15.1 with ghc 8.2.1. I've boiled it down to something that's reproducible (on my machine) with just the two attached files; `MyModule.hs` is stripped down from mon-traversable's `src/Data/Containers.hs`. Not being especially familiar with either mono-traversable or unordered-containers, I have stopped there -- I don't know how to get a dependency-free minimal example the ghc maintainers might be interested in. If you have any suggestions, I'd love to hear them. Or should I contact the unordered-containers maintainers?

## Summary

ghc panic compiling very simple file, stripped down from Data.Containers

## Steps to reproduce

Save the following files in a directory (stripping off the .txt extension):

[MyModule.hs.txt](https://github.com/snoyberg/mono-traversable/files/4301852/MyModule.hs.txt)
[mono-traversable.cabal.txt](https://github.com/snoyberg/mono-traversable/files/4301851/mono-traversable.cabal.txt)

With cabal 1.24 and ghc 8.2.1, do:

```
$ cabal update
$ cabal install --dependencies-only
$ cabal build
```

## Expected behavior

Should compile, and not produce a panic.

## Actual behaviour

```
Building mono-traversable-1.0.15.1...
Preprocessing library mono-traversable-1.0.15.1...
[1 of 1] Compiling MyModule         ( MyModule.hs, dist/build/MyModule.o )

<no location info>: error:
    ghc: panic! (the 'impossible' happened)
  (GHC version 8.2.1 for x86_64-unknown-linux):
	getUnboxedSumName
  513
  Call stack:
      CallStack (from HasCallStack):
        prettyCurrentCallStack, called at compiler/utils/Outputable.hs:1133:58 in ghc:Outputable
        callStackDoc, called at compiler/utils/Outputable.hs:1137:37 in ghc:Outputable
        pprPanic, called at compiler/prelude/KnownUniques.hs:104:5 in ghc:KnownUniques

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

The code from Data.Container looks perfectly run-of-the-mill to me - no odd extensions, nothing that looks unusual about the class or instance. Have I failed to spot something odd about it? Or does unordered-containers do something especially unusual?

## Environment

* GHC version: 8.2.1 (installed from hvr's PPA, here: <https://launchpad.net/~hvr/+archive/ubuntu/ghc>); git commit: [0cee25253f9f2cb4f19f021fd974bdad3c26a80b](https://gitlab.haskell.org/ghc/ghc/commit/0cee25253f9f2cb4f19f021fd974bdad3c26a80b)
* Operating System: Ubuntu 16.04
* System Architecture: x86_64

Any assistance would be appreciated.

**Comment by snoyberg** [comment]
Does it compile with GHC 8.2.2? Overall, I don't have intentions of working on this, but if you find a non-invasive change that works around a GHC bug I'd probably merge it.

**Comment by phlummox** [comment]
It does, yes - so my quick fix has just been to not try and build on Travis using 8.2.1.

**Comment by snoyberg** [comment]
I generally consider `.1` releases of GHC unstable in any event, so I'm even less likely to consider a hacky fix for this. The CI for this repo didn't catch this because we only test with 8.2.2.
