### ISSUE TITLE
New version of `classy-prelude`?

### ISSUE THREAD

**Issue by peterbecich** [snoyberg/mono-traversable#202]
Will there be a new version of `classy-prelude`, corresponding to the recent new version of `mono-traversable`? Thank you

**Comment by snoyberg** [comment]
No plans for a release. I don't see any bounds blocking usage or meaningful changes since the last release. Can you clarify why you're asking?

**Comment by peterbecich** [comment]
Ah yes, I realize that now, thanks. Without having looked at the diff https://github.com/snoyberg/mono-traversable/commit/ea7bdf4796e7e405ed5f3a6ca5d9d23e4c9acb4c#diff-206b4d7c50e3161c185a01ae003e6a0dddde32575eb23bbfdd58dcb190f6fc13 , I just assumed there would be a new release. Closing
