### ISSUE TITLE
RULES have problems substituting polymorphic sequence types

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [snoyberg/mono-traversable#216]
I have been trying to get functions like `Data.Sequences.stripPrefix` to be substituted with the defined rules but it is finicky if used in a function with a polymorphic collection type. It requires persistent inlining of all the functions to the final type specification to not use the "default" implementation.

It seems that a super class would get rid of this problem and allow the more efficient definition to be used.

```
class (IsSequence seq, Eq (Element seq)) => EqElement seq
```

**Comment by BebeSparkelSparkel** [comment]
Any thoughts on this?

**Comment by snoyberg** [comment]
I'm overall -1. Rewrite rules have been notoriously difficult to get to fire reliably, and a breaking API change to account for that would be worth it IMO.

**Comment by BebeSparkelSparkel** [comment]
@snoyberg I'm not sure what "-1" means

**Comment by snoyberg** [comment]
Meaning: overall not in favor.

**Comment by BebeSparkelSparkel** [comment]
Thanks it seemed contrary to your second sentence.
