### ISSUE TITLE
Getting problems in the basic program of Haskell #Haskell

### ISSUE THREAD

**Issue by AkshatSigma** [snoyberg/mono-traversable#220]
I wrote this code in a file name example.hs
main = putStrLn "Hello, world"
now it's showing this error 
akshatkumarsharma@Akshats-Air Haskellproject % ghc example.hs
[1 of 2] Compiling Main             ( example.hs, example.o )

example.hs:1:1: error:
    The IO action ‘main’ is not defined in module ‘Main’
what should I do to solve this, please help and tell as explained as possible, I am a beginner and don't know anything. Have i installed Haskell wrongly?
<img width="1157" alt="Screenshot 2024-04-01 at 19 44 50" src="https://github.com/snoyberg/mono-traversable/assets/162584992/ecc85292-f962-4e7d-bb99-2d432a123e4b">

**Comment by BebeSparkelSparkel** [comment]
Please read https://www.haskell.org/get-started/ and look up specifics of VS Code and GHC Haskell. This the issues for this repository are specifically for the packages 

- minlen
- mono-traversable
- mono-traversable-instances
- chunked-data
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- mutable-containers

Your problem/question is not specific to these packages. If you still have problems after reading the getting started page linked above, post your question on https://discourse.haskell.org/ .
