### ISSUE TITLE
classy-prelude package.yaml and cabal have mismatched versions

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [snoyberg/mono-traversable#230]
package.yaml has 1.5.0.3

classy-prelude.cabal has 1.5.0.2

These are patch versions so it may not be problematic and I see on hackage that it has 1.5.0.3.

**Comment by BebeSparkelSparkel** [comment]
@gregwebs Is it better to add a workflow to ensure that package.yaml and cabal file are synchronized or just delete the package.yaml files?

**Comment by gregwebs** [comment]
hpack can genereate the .cabal file from package.yaml. package.yaml can have some advantages for automatically generating some things in the .cabal file and being easier to do something like write a tool to bump the versions for all packages.

So personally I would add the hpack generation step to the CI. The CI will then fail with the git dirty status check that you added.

**Comment by BebeSparkelSparkel** [comment]
I added the check to the stack build version. I think stack runs hpack, so it think it is good at this point.
