### ISSUE TITLE
Asymptotic performance for `groupAll` / `groupAllOn`

### ISSUE THREAD

**Issue by rehno-lindeque** [snoyberg/mono-traversable#36]
If I'm not mistaken, it looks to me like `groupAll` / `groupAllOn` should have an O(n^2) worst-case performance since they only rely on the `Eq` typeclass, similar to the issue that `nub` has...

A faster implementation based on `Ord` (thanks to @TheunisKotze) might be something like

```haskell
groupAllByOrd = groupBy (((==EQ) . ) . f) . sortBy (f :: a -> a -> Ordering)
```

Or - using the style of `groupAllOn` - perhaps something in the shape of 

```haskell
groupAllOnOrd :: Ord b => (Element seq -> b) -> seq -> [seq]`.
```

Would something like this be worth adding? Also, adding the O(n^2) warning to the documentation would also be good... I could submit a PR for this, but it seems like there's a couple of options. (E.g. interestingly I notice that `ordNubBy` from `classy-prelude` uses two functions  `a -> (b :: Ord)` and `a -> a -> Bool` instead of `a -> a -> Ordering`)

**Comment by snoyberg** [comment]
Closing in favor of PR
