### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by MaxGabriel** [snoyberg/mono-traversable#53]
> However, this should be fairly simple, as it can be seen [in the code](https://hackage.haskell.org/package/mono-traversable/docs/src/Data-MonoTraversable.html#line-234)

The docs provide a link to the mono-traversable source code, but the link is 404ing. I'm not positive what it was pointing to before so I opened an issue instead of a PR.

A potentially more reliable link (though it has the possibility of getting outdated), is to link to some source code on Github at a particular point in time (e.g. https://github.com/snoyberg/mono-traversable/blob/d85e4ed3c11afec2d49c0f4fe2812122a279e5d4/src/Data/MonoTraversable.hs#L233-L234)

**Comment by snoyberg** [comment]
Yeah, that looks reasonable, though that's a bug in Hackage. I'm going to report it separately.

Thanks for all the work on this!

**Comment by snoyberg** [comment]
Never mind, I was able to resolve it, though I think it's pointing to the wrong line of code. @gregwebs?

**Comment by gregwebs** [comment]
fixed in 249ba4bd14d58ac42a59a85a244bd882b61d9b2a
