### ISSUE TITLE
Should mlcons have the same infixr 5 that (++) and (<|) have?

### ISSUE THREAD

**Issue by MaxGabriel** [snoyberg/mono-traversable#56]
`++` and `<|` are defined as `infixr 5`, which enables this style of appending:

```haskell
ghci > 1 : 2 : []
[1,2]
```

but this style isn't possible with `mlcons`:

```
ghci > (1 :: Integer) `mlcons` 2 `mlcons` (toMinLenZero [])
<interactive>:51:1:
    Couldn't match expected type ‘Integer’
                with actual type ‘Element seq0’
    The type variable ‘seq0’ is ambiguous
    In the first argument of ‘System.IO.print’, namely ‘it’
    In a stmt of an interactive GHCi command: System.IO.print it
```

Defining an infixr for `mlcons` fixes this

```haskell
infixr 5 `mlcons`
```

```haskell
ghci > (1 :: Integer) `mlcons` 2 `mlcons` (toMinLenZero [])
MinLen {unMinLen = [1,2]}
```

Would you want a PR for this? I'm not super familiar with defining infix operators but I'm pretty sure this'd be a breaking change.

**Comment by snoyberg** [comment]
Design around fixity is something I am very bad at. I don't see a reason *not* to make this change, and I'd be OK with having a major version bump for this, but maybe @gregwebs will have more insight than I do.

**Comment by gregwebs** [comment]
Looks good to me. I don't see the benefit of avoiding bumping the major version. On the other hand, it is unlikely someone would rely on the existing fixity behavior since it does not work.
