### ISSUE TITLE
Functor instance for MinLen breaks abstraction

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/mono-traversable#82]
Simple demonstration of the problem:

```haskell
import Data.MinLen

len1 :: MinLen (Succ Zero) [()]
len1 = mlcons () (toMinLenZero [])

len0 :: MinLen (Succ Zero) [()]
len0 = fmap (drop 1) len1

main :: IO ()
main = print $ Data.MinLen.head len0
```

Results in:

    Data.MonoTraversable.headEx: empty

I see no option but to release a new major version with the `Functor` instance removed. Slightly tweaked: we can make the `Functor` instance apply only to `MinLen Zero`.

Pinging @gregwebs, in case you have another idea.

**Comment by gregwebs** [comment]
Functor instance should act on what is inside the newtype, not the newtype itself

**Comment by snoyberg** [comment]
If we try to implement that, we'd have to change the kind of `MinLen`, and most likely lose support for monomorphic containers in the process. What you're describing is handled by the `MonoFunctor` instance right now.

**Comment by gregwebs** [comment]
Ok
