### ISSUE TITLE
tailMay?

### ISSUE THREAD

**Issue by JJJollyjim** [snoyberg/mono-traversable#89]
`Data.MonoTraversable` defines `headMay` as a safe counterpart to `headEx`.

`Data.Sequences` defines `tailEx`. Any reason why not `tailMay`?

**Comment by JJJollyjim** [comment]
Looks like the definition is as simple as `(fmap snd) . uncons`. Happy to PR with docs etc if requested.

**Comment by snoyberg** [comment]
Sounds good, thanks!

**Comment by snoyberg** [comment]
Bump
