### ISSUE TITLE
Law given for `GrowingAppend` is wrong.

### ISSUE THREAD

**Issue by bennofs** [snoyberg/mono-traversable#91]
Or there are wrong instances. Consider the following:

```
λ: let s1 = fromList [1]
λ: olength (s1 <> s1)
1
```

But the law for `GrowingAppend` says: `-- | olength (x <> y) >= olength x + olength y`

**Comment by snoyberg** [comment]
That equality is backwards, the law was written incorrectly. Could you send
a PR to fix? Yes, it's just a one character change

**Comment by treeowl** [comment]
Ha. I just came here to report the same thing. I'm still quite unclear on why this class, which does nothing but impose a law, is a superclass of other classes. Is that law really so useful?
