### ISSUE TITLE
Automatic derivation of MonoFunctor for newtypes?

### ISSUE THREAD

**Issue by deepfire** [snoyberg/mono-traversable#96]
`newtype` is cool for increasing type safety, but one has to pay the price of wrapping-rewrapping for mapping over them.  For polymorphic newtypes, one can derive `Functor`, which is very cheap, text-wise -- just an addition of `Functor` into the `deriving` clause.

For monomorphic newtypes we only have `MonoFunctor`, but it cannot be derived, so it becomes the rather cumbersome:
```
newtype Wrap = Wrap Int
type instance Element Wrap = Int
instance MonoFunctor Wrap where
    omap f (Wrap x) = Wrap (f x)
```

So the question is -- can we employ `DeriveAnyClass` or some other technique to allow automatic derivation of `MonoFunctor`?

**Comment by snoyberg** [comment]
Have you tried GeneralizedNewtypeDeriving? I don't know if that will work
with the `default` methods already provided.

**Comment by deepfire** [comment]
@snoyberg, `GeneralizedNewtypeDeriving` doesn't seem to define the methods:
```
newtype  N = N { fromN ∷ [String] }
instance Newtype N [String]
instance Newtype (IO N) (IO [String])
```
->
```
warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘pack’ and ‘unpack’
    • In the instance declaration for
        ‘Newtype (IO N) (IO [String])’.
warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘pack’ and ‘unpack’
    • In the instance declaration for ‘Newtype N [String]’.
```

**Comment by deepfire** [comment]
Disregard the previous comment, as I was trying to define an instance in stead of deriving it.
